'use strict';

// Generated by CoffeeScript 2.3.0
(function () {
  var balanceText;

  balanceText = require('balance-text');

  module.exports = {
    // Add balance text to the element
    bind: function bind(el) {
      return setTimeout(function () {
        return balanceText(el, {
          watch: true
        });
      }, 200);
    },
    // Remove watching
    unbind: function unbind(el) {
      return balanceText(el, {
        watch: false
      });
    }
  };
}).call(undefined);