'use strict';

// Generated by CoffeeScript 2.3.0
(function () {
  var Vue, balanceText;

  Vue = require('vue');

  balanceText = require('balance-text');

  module.exports = {
    // Add balance text to the element
    bind: function bind(el) {
      Vue.nextTick(function () {
        return balanceText(el, {
          watch: true
        });
      });
      // Manually fire again later, like after styles are injected by Webpack
      return setTimeout(function () {
        return balanceText(el);
      }, 300);
    },
    // Update when contents change
    componentUpdated: function componentUpdated(el) {
      return balanceText(el);
    },
    // Remove watching
    unbind: function unbind(el) {
      return balanceText(el, {
        watch: false
      });
    }
  };
}).call(undefined);