'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _vue = require('vue');

var _vue2 = _interopRequireDefault(_vue);

var _balanceText = require('balance-text');

var _balanceText2 = _interopRequireDefault(_balanceText);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// Generated by CoffeeScript 2.3.0
exports.default = {
  // Add balance text to the element
  bind: function bind(el) {
    _vue2.default.nextTick(function () {
      return (0, _balanceText2.default)(el, {
        watch: true
      });
    });
    // Manually fire again later, like after styles are injected by Webpack
    return setTimeout(function () {
      return (0, _balanceText2.default)(el);
    }, 300);
  },
  // Update when contents change
  componentUpdated: function componentUpdated(el) {
    return (0, _balanceText2.default)(el);
  },
  // Remove watching
  unbind: function unbind(el) {
    return (0, _balanceText2.default)(el, {
      watch: false
    });
  }
};